// import type { Metadata } from "next";
// // import localFont from "next/font/local";
// import { Inter } from "next/font/google"
// // import "./globals.css";
// import Navbar from "../../components/navbar";



// // const  geistSans = localFont({
// //   src: "./fonts/GeistVF.woff",
// //   variable: "--font-geist-sans",
// //   weight: "100 900",
// // });
// // const geistMono = localFont({
// //   src: "./fonts/GeistMonoVF.woff",
// //   variable: "--font-geist-mono",
// //   weight: "100 900",
// // });
// const sans = Inter({
//   subsets: ["latin"], variable:
//   "--font-sans"});

//   const mono = Inter({
//     subsets: ["latin"], variable:
//     "--font-sans"});

// export const metadata: Metadata = {
//   title: "Programming with Abdullah",
//   description: "Generated by create next app",
// };
//   export default function Layout({ children }: { children: React.ReactNode }) {
//     return (
//         <html lang="en">
//         <body>
//         <div className={`${sans.variable} ${mono.variable}`}>
          
//           <Navbar/>
//           {children}
//           </div>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; // Ensure globals.css is imported for Tailwind or custom styles
import Navbar from "../../components/navbar";

const sans = Inter({
  subsets: ["latin"],
  variable: "--font-sans"
});

// Agar aapko alag mono font chahiye, to import aur use alag se karen. 
// Agar Inter hi use karna hai to variable name change kar dein:
const mono = Inter({
  subsets: ["latin"],
  variable: "--font-mono"
});

export const metadata: Metadata = {
  title: "Programming with Abdullah",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className={`${sans.variable} ${mono.variable}`}>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
